### ISSUE TITLE
How can I get all testcases in a project

### ISSUE THREAD

**Issue by luisespla** [orenault/TestLink-API-Python-client#21]
Hello,
I have seen that it 's avalaible to get all testcases in a TestPlan but I would like to get all testcases in a project. Is it available?
Best regards

**Comment by orenault** [comment]
You can use the same as for countTestCasesTP:

TestPlans = self.getProjectTestPlans(project['id'])
            for TestPlan in TestPlans:
                TestCases = self.getTestCasesForTestPlan(TestPlan['id'])

=> just define the Project id you need instead of parsing all projects.

**Comment by matthewdy** [comment]
@orenault but if the test project doesn;t contain any testplan , how could i get it ?
