### ISSUE TITLE
Missing Licence Declaration

### ISSUE THREAD

**Issue by lczub** [orenault/TestLink-API-Python-client#4]
The TestLink-API-Python-client project includes currently no LICENCE.txt file. 
Although the source files includes no licence declaration.

Olivier, could you give us feedback, in which license context we could use your code?

Reading your [JinFeng](http://www.sqaopen.net/blog/en/?p=63) abstract, it seems, that you want to use the TestLink-API-Python-client together with robotframework Python code.

Question is, should TestLink-API-Python-client be released like robotframework under the [Apache License 2.0](http://www.apache.org/licenses/LICENSE-2.0) ?

Any other suggestions?

**Comment by orenault** [comment]
Hi Luiko !

Sorry,

i'm ill for some days, blocked at the house.

So, I have some time to check your commits.

First, I'm not agree  with the "author : kereval.com".
kereval is a french IT company...

I don't want a commercial name as "author". If the committer wants to put
his name in the list, ok..
But with his name, not with the brand of his boss...

Second, i've used github a year ago, for the first time.. and not until
then. I didn't remember how it works... :(
So, I have to find how easily merge your commits...

If you have some tips... :))

I have to work on this API and on the jinfeng project again. I've spent the
last year to create my own little IT consultancy firm, it's time for me
come come back to the dev scene... :))

Regards

Olivier

2012/11/26 Luiko Czub notifications@github.com
